/*
- ANSI SQL
- SELECT FROM WHERE
- ORDER BY
- BETWEEN, IN
- LIKE
- CONCAT()
- IS NULL / IS NOT NULL
- IFNULL(?, ?), COALESCE(? ,? ,? ,?)
- GROUP BY HAVING
- RANK(), DENSE_RANK(), ROW_NUMBER(), NITLE(n)
- DML : INSERT, UPDATE, DELETE
- INNER JOIN, OUTER JOIN, CROSS JOIN
- CREATE VIEW {뷰 이름} AS
- ORACLE, MSSQL, MYSQL(MariaDB), IBM DB2
*/